### ISSUE TITLE
Broken layout in IE 9

### ISSUE THREAD

**Issue by smares** [ktsn/vue-range-slider#29]
In search for a replacement for `<input type="range"/>` that doesn't work in IE 9, I came across this Vue component and have the problem that its layout is unfortunately broken in IE 9. It works fine in every other browser tested (latest Chrome, latest Firefox, latest Edge, IE 11, IE 10).

![image](https://user-images.githubusercontent.com/818380/36985566-e34e9b9a-2097-11e8-9200-7dd5199b8d76.png)

**Comment by ktsn** [comment]
This is because vue-range-slider uses transform property. 
I'm not a fan of supporting a browser already ended the official support. Also I'm using transform because it allows the users customize their own style easier.
So I'm not willing to support IE 9, sorry.

But you can customize the default style for your own needs.

**Comment by smares** [comment]
That's a shame, after all, it's actually the main reason why I (and probably others) choose this library over a native `<input type="range"/>` that can already be styled in all modern browsers.

**Comment by smares** [comment]
Quick follow-up: One can simply use autoprefixer with a `ie >= 9` rule which will automatically add `-ms-transform` where `transform` is used.
